CITY_IATA_MAP = {
    # Americas
    "Atlanta, USA (ATL)": "ATL",
    "Boston, USA (BOS)": "BOS",
    "Buenos Aires, Argentina (BUE)": "BUE",
    "Calgary, Canada (YYC)": "YYC",
    "Cancun, Mexico (CUN)": "CUN",
    "Chicago, USA (CHI)": "CHI",
    "Dallas, USA (DFW)": "DFW",
    "Denver, USA (DEN)": "DEN",
    "Honolulu, USA (HNL)": "HNL",
    "Lima, Peru (LIM)": "LIM",
    "Los Angeles, USA (LAX)": "LAX",
    "Mexico City, Mexico (MEX)": "MEX",
    "Miami, USA (MIA)": "MIA",
    "Montreal, Canada (YUL)": "YUL",
    "New York, USA (NYC)": "NYC",
    "Orlando, USA (MCO)": "MCO",
    "Philadelphia, USA (PHL)": "PHL",
    "Rio de Janeiro, Brazil (RIO)": "RIO",
    "San Francisco, USA (SFO)": "SFO",
    "Santiago, Chile (SCL)": "SCL",
    "Sao Paulo, Brazil (SAO)": "SAO",
    "Seattle, USA (SEA)": "SEA",
    "Toronto, Canada (YTO)": "YTO",
    "Vancouver, Canada (YVR)": "YVR",
    "Washington D.C., USA (WAS)": "WAS",
    "Las Vegas, USA (LAS)": "LAS",
    "Phoenix, USA (PHX)": "PHX",
    "San Diego, USA (SAN)": "SAN",
    "San Jose, USA (SJC)": "SJC",
    "Santa Ana, USA (SNA)": "SNA",
    "Oakland, USA (OAK)": "OAK",
    "Portland, USA (PDX)": "PDX",
    "Salt Lake City, USA (SLC)": "SLC",
    "Minneapolis, USA (MSP)": "MSP",
    "Detroit, USA (DTW)": "DTW",
    "Cleveland, USA (CLE)": "CLE",
    "Columbus, USA (CMH)": "CMH",
    "Indianapolis, USA (IND)": "IND",
    "Nashville, USA (BNA)": "BNA",
    "Memphis, USA (MEM)": "MEM",
    "St. Louis, USA (STL)": "STL",
    "Kansas City, USA (MCI)": "MCI",
    "Omaha, USA (OMA)": "OMA",
    "Des Moines, USA (DSM)": "DSM",
    "Oklahoma City, USA (OKC)": "OKC",
    "Tulsa, USA (TUL)": "TUL",
    "Wichita, USA (ICT)": "ICT",
    "Albuquerque, USA (ABQ)": "ABQ",
    "El Paso, USA (ELP)": "ELP",
    "Boise, USA (BOI)": "BOI",
    "Spokane, USA (GEG)": "GEG",
    "Reno, USA (RNO)": "RNO",
    "Palm Springs, USA (PSP)": "PSP",
    "Ontario, USA (ONT)": "ONT",
    "Burbank, USA (BUR)": "BUR",
    "Guadalajara, Mexico (GDL)": "GDL",
    "Monterrey, Mexico (MTY)": "MTY",
    "Puerto Vallarta, Mexico (PVR)": "PVR",
    "Cozumel, Mexico (CZM)": "CZM",
    "Mérida, Mexico (MID)": "MID",
    "Quito, Ecuador (UIO)": "UIO",
    "Guayaquil, Ecuador (GYE)": "GYE",
    "Medellín, Colombia (MDE)": "MDE",
    "Cartagena, Colombia (CTG)": "CTG",
    "Panama City, Panama (PTY)": "PTY",
    "San José, Costa Rica (SJO)": "SJO",
    "San Salvador, El Salvador (SAL)": "SAL",
    "Guatemala City, Guatemala (GUA)": "GUA",
    "Nassau, Bahamas (NAS)": "NAS",
    "Punta Cana, Dominican Republic (PUJ)": "PUJ",
    "Oranjestad, Aruba (AUA)": "AUA",
    "Willemstad, Curaçao (CUR)": "CUR",
    "Anchorage, USA (ANC)": "ANC",
    "Juneau, USA (JNU)": "JNU",
    "Fairbanks, USA (FAI)": "FAI",
    "Bozeman, USA (BZN)": "BZN",
    "Jackson, USA (JAC)": "JAC",
    "Fargo, USA (FAR)": "FAR",
    "Rapid City, USA (RAP)": "RAP",
    "Sioux Falls, USA (FSD)": "FSD",
    "Moncton, Canada (YQM)": "YQM",
    "Saskatoon, Canada (YXE)": "YXE",
    "Regina, Canada (YQR)": "YQR",
    "Winnipeg, Canada (YWG)": "YWG",
    "Thunder Bay, Canada (YQT)": "YQT",
    "Chihuahua, Mexico (CUU)": "CUU",
    "Hermosillo, Mexico (HMO)": "HMO",
    "Tuxtla Gutierrez, Mexico (TGZ)": "TGZ",
    "Leon, Mexico (BJX)": "BJX",
    "Puebla, Mexico (PBC)": "PBC",
    "Aguascalientes, Mexico (AGU)": "AGU",
    "La Paz, Mexico (LAP)": "LAP",
    "Santa Cruz, Bolivia (VVI)": "VVI",
    "Sucre, Bolivia (SRE)": "SRE",
    "Arequipa, Peru (AQP)": "AQP",
    "Cusco, Peru (CUZ)": "CUZ",
    "Trujillo, Peru (TRU)": "TRU",
    "Iquitos, Peru (IQT)": "IQT",
    "Santa Marta, Colombia (SMR)": "SMR",
    "Bucaramanga, Colombia (BGA)": "BGA",
    "Pereira, Colombia (PEI)": "PEI",
    "Cali, Colombia (CLO)": "CLO",
    "Montevideo, Uruguay (MVD)": "MVD",
    "Asuncion, Paraguay (ASU)": "ASU",
    "San Antonio, USA (SAT)": "SAT",
    "Austin, USA (AUS)": "AUS",
    "Houston, USA (HOU)": "HOU",
    "New Orleans, USA (MSY)": "MSY",
    "San Juan, Puerto Rico (SJU)": "SJU",
    "Tampa, USA (TPA)": "TPA",
    "St. Petersburg, USA (PIE)": "PIE",
    "Fort Lauderdale, USA (FLL)": "FLL",
    "West Palm Beach, USA (PBI)": "PBI",
    "Dayton, USA (DAY)": "DAY",
    "Toledo, USA (TOL)": "TOL",
    "Akron, USA (CAK)": "CAK",
    "Lexington, USA (LEX)": "LEX",
    "Louisville, USA (SDF)": "SDF",
    "Charleston, USA (CHS)": "CHS",
    "Savannah, USA (SAV)": "SAV",
    "Greenville, USA (GSP)": "GSP",
    "Knoxville, USA (TYS)": "TYS",
    "Chattanooga, USA (CHA)": "CHA",
    "Huntsville, USA (HSV)": "HSV",
    "Mobile, USA (MOB)": "MOB",
    "Pensacola, USA (PNS)": "PNS",
    "Santa Fe, USA (SAF)": "SAF",
    "Durango, USA (DRO)": "DRO",
    "Flagstaff, USA (FLG)": "FLG",
    "Yuma, USA (YUM)": "YUM",
    "La Paz, Bolivia (LPB)": "LPB",
    "Cochabamba, Bolivia (CBB)": "CBB",
    "Barranquilla, Colombia (BAQ)": "BAQ",
    "Manizales, Colombia (MZL)": "MZL",
    "Cuenca, Ecuador (CUE)": "CUE",
    "Salta, Argentina (SLA)": "SLA",
    "Mendoza, Argentina (MDZ)": "MDZ",
    "Ushuaia, Argentina (USH)": "USH",
    "Punta Arenas, Chile (PUQ)": "PUQ",
    "Antofagasta, Chile (ANF)": "ANF",

    # Europe
    "Amsterdam, Netherlands (AMS)": "AMS",
    "Athens, Greece (ATH)": "ATH",
    "Barcelona, Spain (BCN)": "BCN",
    "Berlin, Germany (BER)": "BER",
    "Brussels, Belgium (BRU)": "BRU",
    "Copenhagen, Denmark (CPH)": "CPH",
    "Dublin, Ireland (DUB)": "DUB",
    "Edinburgh, UK (EDI)": "EDI",
    "Frankfurt, Germany (FRA)": "FRA",
    "Geneva, Switzerland (GVA)": "GVA",
    "Helsinki, Finland (HEL)": "HEL",
    "Istanbul, Turkey (IST)": "IST",
    "Lisbon, Portugal (LIS)": "LIS",
    "London, UK (LON)": "LON",
    "Madrid, Spain (MAD)": "MAD",
    "Manchester, UK (MAN)": "MAN",
    "Milan, Italy (MIL)": "MIL",
    "Moscow, Russia (MOW)": "MOW",
    "Munich, Germany (MUC)": "MUC",
    "Oslo, Norway (OSL)": "OSL",
    "Paris, France (PAR)": "PAR",
    "Prague, Czechia (PRG)": "PRG",
    "Rome, Italy (ROM)": "ROM",
    "St. Petersburg, Russia (LED)": "LED",
    "Stockholm, Sweden (STO)": "STO",
    "Vienna, Austria (VIE)": "VIE",
    "Warsaw, Poland (WAW)": "WAW",
    "Zurich, Switzerland (ZRH)": "ZRH",
    "Gothenburg, Sweden (GOT)": "GOT",
    "Malmö, Sweden (MMX)": "MMX",
    "Billund, Denmark (BLL)": "BLL",
    "Aalborg, Denmark (AAL)": "AAL",
    "Tallinn, Estonia (TLL)": "TLL",
    "Riga, Latvia (RIX)": "RIX",
    "Vilnius, Lithuania (VNO)": "VNO",
    "Kraków, Poland (KRK)": "KRK",
    "Gdańsk, Poland (GDN)": "GDN",
    "Wrocław, Poland (WRO)": "WRO",
    "Budapest, Hungary (BUD)": "BUD",
    "Bucharest, Romania (OTP)": "OTP",
    "Cluj-Napoca, Romania (CLJ)": "CLJ",
    "Sofia, Bulgaria (SOF)": "SOF",
    "Belgrade, Serbia (BEG)": "BEG",
    "Thessaloniki, Greece (SKG)": "SKG",
    "Heraklion, Greece (HER)": "HER",
    "Rhodes, Greece (RHO)": "RHO",
    "Naples, Italy (NAP)": "NAP",
    "Florence, Italy (FLR)": "FLR",
    "Bologna, Italy (BLQ)": "BLQ",
    "Pisa, Italy (PSA)": "PSA",
    "Turin, Italy (TRN)": "TRN",
    "Verona, Italy (VRN)": "VRN",
    "Innsbruck, Austria (INN)": "INN",
    "Salzburg, Austria (SZG)": "SZG",
    "Graz, Austria (GRZ)": "GRZ",
    "Ljubljana, Slovenia (LJU)": "LJU",
    "Zagreb, Croatia (ZAG)": "ZAG",
    "Split, Croatia (SPU)": "SPU",
    "Dubrovnik, Croatia (DBV)": "DBV",
    "Tirana, Albania (TIA)": "TIA",
    "Sarajevo, Bosnia and Herzegovina (SJJ)": "SJJ",
    "Valencia, Spain (VLC)": "VLC",
    "Alicante, Spain (ALC)": "ALC",
    "Palma de Mallorca, Spain (PMI)": "PMI",
    "Ibiza, Spain (IBZ)": "IBZ",
    "Reykjavik, Iceland (KEF)": "KEF",
    "Hamburg, Germany (HAM)": "HAM",
    "Nice, France (NCE)": "NCE",
    "Bergen, Norway (BGO)": "BGO",
    "Luxembourg City, Luxembourg (LUX)": "LUX",
    "Basel, Switzerland (BSL)": "BSL",
    "Bern, Switzerland (BRN)": "BRN",
    "Turku, Finland (TKU)": "TKU",
    "Tampere, Finland (TMP)": "TMP",
    "Oulu, Finland (OUL)": "OUL",
    "Bodø, Norway (BOO)": "BOO",
    "Tromsø, Norway (TOS)": "TOS",
    "Umeå, Sweden (UME)": "UME",
    "Visby, Sweden (VBY)": "VBY",
    "Odense, Denmark (ODE)": "ODE",
    "Esbjerg, Denmark (EBJ)": "EBJ",
    "Groningen, Netherlands (GRQ)": "GRQ",
    "Eindhoven, Netherlands (EIN)": "EIN",
    "Rotterdam, Netherlands (RTM)": "RTM",
    "Brest, France (BES)": "BES",
    "Rennes, France (RNS)": "RNS",
    "Limoges, France (LIG)": "LIG",
    "Zaragoza, Spain (ZAZ)": "ZAZ",
    "Murcia, Spain (RMU)": "RMU",
    "Almeria, Spain (LEI)": "LEI",
    "Jerez, Spain (XRY)": "XRY",
    "Trieste, Italy (TRS)": "TRS",
    "Perugia, Italy (PEG)": "PEG",
    "Ancona, Italy (AOI)": "AOI",
    "Lamezia Terme, Italy (SUF)": "SUF",
    "Bari, Italy (BRI)": "BRI",
    "Cagliari, Italy (CAG)": "CAG",
    "Olbia, Italy (OLB)": "OLB",
    "Plovdiv, Bulgaria (PDV)": "PDV",
    "Varna, Bulgaria (VAR)": "VAR",
    "Timisoara, Romania (TSR)": "TSR",
    "Oradea, Romania (OMR)": "OMR",
    "Kosice, Slovakia (KSC)": "KSC",
    "Krasnodar, Russia (KRR)": "KRR",
    "Sochi, Russia (AER)": "AER",
    "Seville, Spain (SVQ)": "SVQ",
    "Granada, Spain (GRX)": "GRX",
    "Malaga, Spain (AGP)": "AGP",
    "Bilbao, Spain (BIO)": "BIO",
    "Santander, Spain (SDR)": "SDR",
    "Faro, Portugal (FAO)": "FAO",
    "Porto, Portugal (OPO)": "OPO",
    "Coimbra, Portugal (CBP)": "CBP",
    "Lyon, France (LYS)": "LYS",
    "Marseille, France (MRS)": "MRS",
    "Toulouse, France (TLS)": "TLS",
    "Montpellier, France (MPL)": "MPL",
    "Avignon, France (AVN)": "AVN",
    "Cologne, Germany (CGN)": "CGN",
    "Stuttgart, Germany (STR)": "STR",
    "Dresden, Germany (DRS)": "DRS",
    "Leipzig, Germany (LEJ)": "LEJ",
    "Nuremberg, Germany (NUE)": "NUE",
    "Leeds, UK (LBA)": "LBA",
    "Bristol, UK (BRS)": "BRS",
    "Cardiff, UK (CWL)": "CWL",
    "Belfast, UK (BFS)": "BFS",
    "Cork, Ireland (ORK)": "ORK",
    "Limerick, Ireland (SNN)": "SNN",
    "Bratislava, Slovakia (BTS)": "BTS",
    "Katowice, Poland (KTW)": "KTW",
    "Lodz, Poland (LCJ)": "LCJ",
    "Poznan, Poland (POZ)": "POZ",
    "Brno, Czechia (BRQ)": "BRQ",
    "Ostrava, Czechia (OSR)": "OSR",
    "Skopje, North Macedonia (SKP)": "SKP",

    # Asia and Middle East
    "Abu Dhabi, UAE (AUH)": "AUH",
    "Amman, Jordan (AMM)": "AMM",
    "Bangkok, Thailand (BKK)": "BKK",
    "Beijing, China (PEK)": "PEK",
    "Bengaluru, India (BLR)": "BLR",
    "Chengdu, China (CTU)": "CTU",
    "Delhi, India (DEL)": "DEL",
    "Denpasar, Indonesia (DPS)": "DPS",
    "Doha, Qatar (DOH)": "DOH",
    "Dubai, UAE (DXB)": "DXB",
    "Ho Chi Minh City, Vietnam (SGN)": "SGN",
    "Hong Kong (HKG)": "HKG",
    "Hyderabad, India (HYD)": "HYD",
    "Jakarta, Indonesia (CGK)": "CGK",
    "Kuala Lumpur, Malaysia (KUL)": "KUL",
    "Kuwait City, Kuwait (KWI)": "KWI",
    "Manila, Philippines (MNL)": "MNL",
    "Mumbai, India (BOM)": "BOM",
    "Osaka, Japan (OSA)": "OSA",
    "Phuket, Thailand (HKT)": "HKT",
    "Riyadh, Saudi Arabia (RUH)": "RUH",
    "Seoul, South Korea (SEL)": "SEL",
    "Shanghai, China (SHA)": "SHA",
    "Singapore (SIN)": "SIN",
    "Taipei, Taiwan (TPE)": "TPE",
    "Tokyo, Japan (TYO)": "TYO",
    "Pune, India (PNQ)": "PNQ",
    "Kolkata, India (CCU)": "CCU",
    "Ahmedabad, India (AMD)": "AMD",
    "Kochi, India (COK)": "COK",
    "Trivandrum, India (TRV)": "TRV",
    "Chandigarh, India (IXC)": "IXC",
    "Patna, India (PAT)": "PAT",
    "Varanasi, India (VNS)": "VNS",
    "Jaipur, India (JAI)": "JAI",
    "Udaipur, India (UDR)": "UDR",
    "Nagpur, India (NAG)": "NAG",
    "Chennai, India (MAA)": "MAA",
    "Goa, India (GOI)": "GOI",
    "Indore, India (IDR)": "IDR",
    "Jodhpur, India (JDH)": "JDH",
    "Agra, India (AGR)": "AGR",
    "Amritsar, India (ATQ)": "ATQ",
    "Aurangabad, India (IXU)": "IXU",
    "Madurai, India (IXM)": "IXM",
    "Tirupati, India (TIR)": "TIR",
    "Leh, India (IXL)": "IXL",
    "Dehradun, India (DED)": "DED",
    "Jammu, India (IXJ)": "IXJ",
    "Surat, India (STV)": "STV",
    "Vadodara, India (BDQ)": "BDQ",
    "Rajkot, India (RAJ)": "RAJ",
    "Bhopal, India (BHO)": "BHO",
    "Raipur, India (RPR)": "RPR",
    "Ranchi, India (IXR)": "IXR",
    "Puducherry, India (PNY)": "PNY",
    "Manali, India (KUU)": "KUU",
    "Penang, Malaysia (PEN)": "PEN",
    "Langkawi, Malaysia (LGK)": "LGK",
    "Surabaya, Indonesia (SUB)": "SUB",
    "Bandung, Indonesia (BDO)": "BDO",
    "Medan, Indonesia (KNO)": "KNO",
    "Hanoi, Vietnam (HAN)": "HAN",
    "Da Nang, Vietnam (DAD)": "DAD",
    "Nha Trang, Vietnam (CXR)": "CXR",
    "Phnom Penh, Cambodia (PNH)": "PNH",
    "Siem Reap, Cambodia (REP)": "REP",
    "Incheon, South Korea (ICN)": "ICN",
    "Busan, South Korea (PUS)": "PUS",
    "Jeju, South Korea (CJU)": "CJU",
    "Karachi, Pakistan (KHI)": "KHI",
    "Lahore, Pakistan (LHE)": "LHE",
    "Islamabad, Pakistan (ISB)": "ISB",
    "Muscat, Oman (MCT)": "MCT",
    "Tehran, Iran (IKA)": "IKA",
    "Jeddah, Saudi Arabia (JED)": "JED",
    "Dammam, Saudi Arabia (DMM)": "DMM",
    "Kathmandu, Nepal (KTM)": "KTM",
    "Colombo, Sri Lanka (CMB)": "CMB",
    "Dhaka, Bangladesh (DAC)": "DAC",
    "Almaty, Kazakhstan (ALA)": "ALA",
    "Tashkent, Uzbekistan (TAS)": "TAS",
    "Samarkand, Uzbekistan (SKD)": "SKD",
    "Baku, Azerbaijan (GYD)": "GYD",
    "Batumi, Georgia (BUS)": "BUS",
    "Yerevan, Armenia (EVN)": "EVN",
    "Ulaanbaatar, Mongolia (ULN)": "ULN",
    "Luang Prabang, Laos (LPQ)": "LPQ",
    "Vientiane, Laos (VTE)": "VTE",
    "Mandalay, Myanmar (MDL)": "MDL",
    "Bagan, Myanmar (NYU)": "NYU",
    "Daegu, South Korea (TAE)": "TAE",
    "Gwangju, South Korea (KWJ)": "KWJ",
    "Fukuoka, Japan (FUK)": "FUK",
    "Sendai, Japan (SDJ)": "SDJ",
    "Sapporo, Japan (CTS)": "CTS",
    "Kagoshima, Japan (KOJ)": "KOJ",
    "Okayama, Japan (OKJ)": "OKJ",
    "Kota Kinabalu, Malaysia (BKI)": "BKI",
    "Kuching, Malaysia (KCH)": "KCH",
    "Pontianak, Indonesia (PNK)": "PNK",
    "Balikpapan, Indonesia (BPN)": "BPN",
    "Makassar, Indonesia (UPG)": "UPG",
    "Padang, Indonesia (PDG)": "PDG",
    "Pekanbaru, Indonesia (PKU)": "PKU",
    "Lucknow, India (LKO)": "LKO",
    "Kanpur, India (KNU)": "KNU",
    "Guwahati, India (GAU)": "GAU",
    "Imphal, India (IMF)": "IMF",
    "Aizawl, India (AJL)": "AJL",
    "Shillong, India (SHL)": "SHL",
    "Silchar, India (IXS)": "IXS",
    "Dibrugarh, India (DIB)": "DIB",
    "Jorhat, India (JRH)": "JRH",
    "Dimapur, India (DMU)": "DMU",
    "Agartala, India (IXA)": "IXA",
    "Vijayawada, India (VGA)": "VGA",
    "Visakhapatnam, India (VTZ)": "VTZ",
    "Rajahmundry, India (RJA)": "RJA",
    "Tiruchirappalli, India (TRZ)": "TRZ",
    "Coimbatore, India (CJB)": "CJB",
    "Salem, India (SXV)": "SXV",
    "Thoothukudi, India (TCR)": "TCR",
    "Mysuru, India (MYQ)": "MYQ",
    "Hubli, India (HBX)": "HBX",
    "Belagavi, India (IXG)": "IXG",
    "Kalaburagi, India (GBI)": "GBI",
    "Mangalore, India (IXE)": "IXE",
    "Udupi, India (UDU)": "UDU",
    "Batam, Indonesia (BTH)": "BTH",
    "Yogyakarta, Indonesia (JOG)": "JOG",
    "Solo, Indonesia (SOC)": "SOC",
    "Semarang, Indonesia (SRG)": "SRG",
    "Palembang, Indonesia (PLM)": "PLM",
    "Hat Yai, Thailand (HDY)": "HDY",
    "Chiang Rai, Thailand (CEI)": "CEI",
    "Udon Thani, Thailand (UTH)": "UTH",
    "Vladivostok, Russia (VVO)": "VVO",
    "Khabarovsk, Russia (KHV)": "KHV",
    "Tabuk, Saudi Arabia (TUU)": "TUU",
    "Yanbu, Saudi Arabia (YNB)": "YNB",
    "Abha, Saudi Arabia (AHB)": "AHB",
    "Taif, Saudi Arabia (TIF)": "TIF",
    "Irkutsk, Russia (IKT)": "IKT",
    "Novokuznetsk, Russia (NOZ)": "NOZ",
    "Al Ula, Saudi Arabia (ULH)": "ULH",

    # Africa and Oceania
    "Accra, Ghana (ACC)": "ACC",
    "Adelaide, Australia (ADL)": "ADL",
    "Auckland, New Zealand (AKL)": "AKL",
    "Cairo, Egypt (CAI)": "CAI",
    "Cape Town, South Africa (CPT)": "CPT",
    "Casablanca, Morocco (CMN)": "CMN",
    "Durban, South Africa (DUR)": "DUR",
    "Johannesburg, South Africa (JNB)": "JNB",
    "Marrakesh, Morocco (RAK)": "RAK",
    "Melbourne, Australia (MEL)": "MEL",
    "Nairobi, Kenya (NBO)": "NBO",
    "Perth, Australia (PER)": "PER",
    "Sydney, Australia (SYD)": "SYD",
    "Tunis, Tunisia (TUN)": "TUN",
    "Wellington, New Zealand (WLG)": "WLG",
    "Lagos, Nigeria (LOS)": "LOS",
    "Abuja, Nigeria (ABV)": "ABV",
    "Port Harcourt, Nigeria (PHC)": "PHC",
    "Luanda, Angola (LAD)": "LAD",
    "Maputo, Mozambique (MPM)": "MPM",
    "Gaborone, Botswana (GBE)": "GBE",
    "Windhoek, Namibia (WDH)": "WDH",
    "Harare, Zimbabwe (HRE)": "HRE",
    "Addis Ababa, Ethiopia (ADD)": "ADD",
    "Dakar, Senegal (DSS)": "DSS",
    "Brisbane, Australia (BNE)": "BNE",
    "Gold Coast, Australia (OOL)": "OOL",
    "Cairns, Australia (CNS)": "CNS",
    "Hobart, Australia (HBA)": "HBA",
    "Launceston, Australia (LST)": "LST",
    "Christchurch, New Zealand (CHC)": "CHC",
    "Dunedin, New Zealand (DUD)": "DUD",
    "Nadi, Fiji (NAN)": "NAN",
    "Papeete, French Polynesia (PPT)": "PPT",
    "Port Moresby, Papua New Guinea (POM)": "POM",
    "Malé, Maldives (MLE)": "MLE",
    "Port Elizabeth, South Africa (PLZ)": "PLZ",
    "East London, South Africa (ELS)": "ELS",
    "Polokwane, South Africa (PTG)": "PTG",
    "Livingstone, Zambia (LVI)": "LVI",
    "Ndola, Zambia (NLA)": "NLA",
    "Entebbe, Uganda (EBB)": "EBB",
    "Kigali, Rwanda (KGL)": "KGL",
    "Bujumbura, Burundi (BJM)": "BJM",
    "Moroni, Comoros (HAH)": "HAH",
    "Antananarivo, Madagascar (TNR)": "TNR",
    "Nosy Be, Madagascar (NOS)": "NOS",
    "Townsville, Australia (TSV)": "TSV",
    "Rockhampton, Australia (ROK)": "ROK",
    "Darwin, Australia (DRW)": "DRW",
    "Alice Springs, Australia (ASP)": "ASP",
    "Queenstown, New Zealand (ZQN)": "ZQN",
    "Rotorua, New Zealand (ROT)": "ROT",
    "Invercargill, New Zealand (IVC)": "IVC",
    "Apia, Samoa (APW)": "APW",
    "Honiara, Solomon Islands (HIR)": "HIR",
    "Port Louis, Mauritius (MRU)": "MRU",
    "Mahe, Seychelles (SEZ)": "SEZ",
    "Lilongwe, Malawi (LLW)": "LLW",
    "Blantyre, Malawi (BLZ)": "BLZ",
    "Lusaka, Zambia (LUN)": "LUN",
    "Bulawayo, Zimbabwe (BUQ)": "BUQ",
    "Francistown, Botswana (FRW)": "FRW",
    "Walvis Bay, Namibia (WVB)": "WVB",
    "Swakopmund, Namibia (SWP)": "SWP",
    "Arusha, Tanzania (ARK)": "ARK",
    "Kilimanjaro, Tanzania (JRO)": "JRO",
    "Mombasa, Kenya (MBA)": "MBA",
    "Zanzibar City, Tanzania (ZNZ)": "ZNZ",
    "Dar es Salaam, Tanzania (DAR)": "DAR",
    "Canberra, Australia (CBR)": "CBR",
    "Albury, Australia (ABX)": "ABX",
    "Wagga Wagga, Australia (WGA)": "WGA",
    "Dubbo, Australia (DBO)": "DBO",
    "Kalgoorlie, Australia (KGI)": "KGI",
    "Broome, Australia (BME)": "BME",
    "Nelson, New Zealand (NSN)": "NSN",
    "Taupo, New Zealand (TUO)": "TUO",
    "Whangarei, New Zealand (WRE)": "WRE",
    "Timaru, New Zealand (TIU)": "TIU",

}

INDIA_IATA_CODES = {
    iata
    for city, iata in CITY_IATA_MAP.items()
    if ", India (" in city
}
