INDIAN_AIRLINES = [
    "IndiGo",
    "Air India",
    "Vistara",
    "SpiceJet",
    "Akasa Air"
]

INTERNATIONAL_AIRLINES = [
    "Qatar Airways","Emirates","Singapore Airlines","Lufthansa",
    "British Airways","Etihad Airways","Turkish Airlines",
    "Cathay Pacific","KLM Royal Dutch Airlines","Air France",
    "ANA","Japan Airlines","Korean Air","United Airlines",
    "Delta Air Lines","American Airlines","Air Canada"
]

REGION_AIRLINES = {
    "ASIA_MIDDLE_EAST": [
        "Emirates","Qatar Airways","Etihad Airways",
        "Singapore Airlines","Air India","IndiGo",
        "Cathay Pacific","ANA","Japan Airlines"
    ],

    "EUROPE": [
        "British Airways","Lufthansa","Air France",
        "KLM Royal Dutch Airlines","Turkish Airlines",
        "SWISS","Austrian Airlines","Finnair"
    ],

    "AMERICAS": [
        "United Airlines","Air India",
        "Delta Air Lines","American Airlines",
        "Air Canada","British Airways",
        "Lufthansa","Air France"
    ],

    "AFRICA_OCEANIA": [
        "Emirates","Qatar Airways",
        "Ethiopian Airlines","Kenya Airways",
        "Qantas","Air New Zealand"
    ]
}

PREMIUM_AIRLINES = [
    "Emirates", "Qatar Airways", "Singapore Airlines", "Lufthansa"
]

AMERICAS = {
    "ATL","BOS","BUE","YYC","CUN","CHI","DFW","DEN","HNL","LIM","LAX","MEX",
    "MIA","YUL","NYC","MCO","PHL","RIO","SFO","SCL","SAO","SEA","YTO","YVR",
    "WAS","LAS","PHX","SAN","SJC","SNA","OAK","PDX","SLC","MSP","DTW","CLE",
    "CMH","IND","BNA","MEM","STL","MCI","OMA","DSM","OKC","TUL","ICT","ABQ",
    "ELP","BOI","GEG","RNO","PSP","ONT","BUR","GDL","MTY","PVR","CZM","MID",
    "UIO","GYE","MDE","CTG","PTY","SJO","SAL","GUA","NAS","PUJ","AUA","CUR",
    "ANC","JNU","FAI","BZN","JAC","FAR","RAP","FSD","YQM","YXE","YQR","YWG",
    "YQT","CUU","HMO","TGZ","BJX","PBC","AGU","LAP","VVI","SRE","AQP","CUZ",
    "TRU","IQT","SMR","BGA","PEI","CLO","MVD","ASU","SAT","AUS","HOU","MSY",
    "SJU","TPA","PIE","FLL","PBI","DAY","TOL","CAK","LEX","SDF","CHS","SAV",
    "GSP","TYS","CHA","HSV","MOB","PNS","SAF","DRO","FLG","YUM","LPB","CBB",
    "BAQ","MZL","CUE","SLA","MDZ","USH","PUQ","ANF"
}

EUROPE = {
    "AMS","ATH","BCN","BER","BRU","CPH","DUB","EDI","FRA","GVA","HEL","IST",
    "LIS","LON","MAD","MAN","MIL","MOW","MUC","OSL","PAR","PRG","ROM","LED",
    "STO","VIE","WAW","ZRH","GOT","MMX","BLL","AAL","TLL","RIX","VNO","KRK",
    "GDN","WRO","BUD","OTP","CLJ","SOF","BEG","SKG","HER","RHO","NAP","FLR",
    "BLQ","PSA","TRN","VRN","INN","SZG","GRZ","LJU","ZAG","SPU","DBV","TIA",
    "SJJ","VLC","ALC","PMI","IBZ","KEF","HAM","NCE","BGO","LUX","BSL","BRN",
    "TKU","TMP","OUL","BOO","TOS","UME","VBY","ODE","EBJ","GRQ","EIN","RTM",
    "BES","RNS","LIG","ZAZ","RMU","LEI","XRY","TRS","PEG","AOI","SUF","BRI",
    "CAG","OLB","PDV","VAR","TSR","OMR","KSC","KRR","AER","SVQ","GRX","AGP",
    "BIO","SDR","FAO","OPO","CBP","LYS","MRS","TLS","MPL","AVN","CGN","STR",
    "DRS","LEJ","NUE","LBA","BRS","CWL","BFS","ORK","SNN","BTS","KTW","LCJ",
    "POZ","BRQ","OSR","SKP"
}

ASIA_MIDDLE_EAST = {
    "AUH","AMM","BKK","PEK","BLR","CTU","DEL","DPS","DOH","DXB","SGN","HKG",
    "HYD","CGK","KUL","KWI","MNL","BOM","OSA","HKT","RUH","SEL","SHA","SIN",
    "TPE","TYO","PNQ","CCU","AMD","COK","TRV","IXC","PAT","VNS","JAI","UDR",
    "NAG","MAA","GOI","IDR","JDH","AGR","ATQ","IXU","IXM","TIR","IXL","DED",
    "IXJ","STV","BDQ","RAJ","BHO","RPR","IXR","PNY","KUU","PEN","LGK","SUB",
    "BDO","KNO","HAN","DAD","CXR","PNH","REP","ICN","PUS","CJU","KHI","LHE",
    "ISB","MCT","IKA","JED","DMM","KTM","CMB","DAC","ALA","TAS","SKD","GYD",
    "BUS","EVN","ULN","LPQ","VTE","MDL","NYU","TAE","KWJ","FUK","SDJ","CTS",
    "KOJ","OKJ","BKI","KCH","PNK","BPN","UPG","PDG","PKU","LKO","KNU","GAU",
    "IMF","AJL","SHL","IXS","DIB","JRH","DMU","IXA","VGA","VTZ","RJA","TRZ",
    "CJB","SXV","TCR","MYQ","HBX","IXG","GBI","IXE","UDU","BTH","JOG","SOC",
    "SRG","PLM","HDY","CEI","UTH","VVO","KHV","TUU","YNB","AHB","TIF","IKT",
    "NOZ","ULH"
}
AFRICA_OCEANIA = {
    "ACC","ADL","AKL","CAI","CPT","CMN","DUR","JNB","RAK","MEL","NBO","PER",
    "SYD","TUN","WLG","LOS","ABV","PHC","LAD","MPM","GBE","WDH","HRE","ADD",
    "DSS","BNE","OOL","CNS","HBA","LST","CHC","DUD","NAN","PPT","POM","MLE",
    "PLZ","ELS","PTG","LVI","NLA","EBB","KGL","BJM","HAH","TNR","NOS","TSV",
    "ROK","DRW","ASP","ZQN","ROT","IVC","APW","HIR","MRU","SEZ","LLW","BLZ",
    "LUN","BUQ","FRW","WVB","SWP","ARK","JRO","MBA","ZNZ","DAR","CBR","ABX",
    "WGA","DBO","KGI","BME","NSN","TUO","WRE","TIU"
}

FALLBACK_HOTEL_NAMES = {

    # Americas
    "ATL": "Peachtree Business Lodge",
    "BOS": "Beacon Hill Historic Stay",
    "BUE": "Recoleta Design Suites",
    "YYC": "Hotel Le Germain",
    "CUN": "Riviera Maya Beach Resort",
    "CHI": "The Peninsula",
    "DFW": "The Ritz-Carlton",
    "DEN": "The Crawford Hotel",
    "HNL": "Halekulani Hotel",
    "LIM": "Hilton Lima Miraflores",
    "LAX": "Hollywood Hills Budget Hotel",
    "MEX": "Polanco Business Residence",
    "MIA": "Nobu Hotel Miami Beach",
    "YUL": "Sofitel Montreal Golden Mile",
    "NYC": "Midtown Executive Suites",
    "MCO": "Copacabana Palace",
    "PHL": "The Rittenhouse Hotel",
    "RIO": "Emiliano Rio, an SLH Hotel",
    "SFO": "Fisherman's Wharf Lodge",
    "SCL": "Mandarin Oriental",
    "SAO": "JW Marriott Hotel",
    "SEA": "Hilton Garden Inn",
    "YTO": "Fairmont Royal York",
    "YVR": "Rosewood Hotel Georgia",
    "WAS": "Capitol Hill Budget Stay",
    "LAS": "Caesars Palace",
    "PHX": "Best Western DownTown",
    "SAN": "Samesun Ocean Beach",
    "SJC": "Holiday Inn",
    "SNA": "Hilton Orange Country",
    "OAK": "Bay Breeze Inn",
    "PDX": "The Hoxton",
    "SLC": "The Little America Hotel",
    "MSP": "The New Victorian Mansion Bed",
    "DTW": "Cambria Hotel Detroit DownTown",
    "CLE": "Best Western Plus Strongsville",
    "CMH": "Wyndham Columbus",
    "IND": "Marriott DownTown",
    "BNA": "Comfort inn DownTown",
    "MEM": "Big Cypress Lodge",
    "STL": "Hampton Inn",
    "MCI": "The Truitt",
    "OMA": "Best Western Plus Midwest Inn",
    "DSM": "Hotel Fort Des Moines",
    "OKC": "Omni Oklahoma City Hotel",
    "TUL": "The Mayo Hotel",
    "ICT": "SpringHill Suites by Marriott",
    "ABQ": "Hampton Inn & Suites",
    "ELP": "La Quinta Inn",
    "BOI": "The Grove Hotel",
    "GEG": "The Davenport Grand",
    "RNO": "Grand Sierra Resort and Casino",
    "PSP": "Indian Wells Resort Hotel",
    "ONT": "Best Western Pine Tree Motel",
    "BUR": "Coast Burbank Hotel",
    "GDL": "Hotel Riu Plaza",
    "MTY": "Hotel Safi Royal Luxury Valle",
    "PVR": "Grand Miramar Resort",
    "CZM": "The Westin Cozumel",
    "MID": "Fiesta Americana",
    "UIO": "Hotel Plaza Grande",
    "GYE": "Oro Verde Guayaquil",
    "MDE": "Marquee Hotel Medellin",
    "CTG": "Almirante Hotel",
    "PTY": "Waldorf Astoria",
    "SJO": "Hilton Garden Inn",
    "SAL": "Sheraton Presidente",
    "GUA": "Westin Camino Real",
    "NAS": "Rosewood Baha Mar",
    "PUJ": "Melia Caribe Beach Resort",
    "AUA": "Renaissance Wind Creek",
    "CUR": "The Ritz Residence",
    "ANC": "Hotel Captain Cook",
    "JNU": "Best Western Country Lane Inn",
    "FAI": "Clarion Hotel & Suites",
    "BZN": "Kimpton Armory Hotel",
    "JAC": "Wyoming Inn of Jackson Hole",
    "FAR": "Holiday Inn Fargo",
    "RAP": "Grand Gateway Hotel",
    "FSD": "Best Western Empire Towers",
    "YQM": "Crowne Plaza Moncton Downtown",
    "YXE": "The James Hotel",
    "YQR": "DoubleTree by Hilton Hotel",
    "YWG": "The Fort Garry Hotel",
    "YQT": "Delta Hotels Thunder Bay",
    "CUU": "Courtyard by Marriott",
    "HMO": "Hotel Boutique Villa Toscana",
    "TGZ": "Fiesta Inn Tuxtla Fashion Mall",
    "BJX": "Hyatt Centric Campestre",
    "PBC": "Casona de Ios Sapos Hotel Boutique",
    "AGU": "Gran Hotel Hacienda de La Noria",
    "LAP": "Hotel Indigo La Paz Puerta Cortes",
    "VVI": "Radisson Hotel",
    "SRE": "Mi Pueblo Samary",
    "AQP": "Casa Andina Premium",
    "CUZ": "Palacio del Inka Hotel",
    "TRU": "Hotel El Gran Marques",
    "IQT": "Treehouse Lodge",
    "SMR": "Hotel Boutique Don Pepe",
    "BGA": "Hotel Dann Carlton",
    "PEI": "GHL Hotel Abadia Plaza",
    "CLO": "Hotel Torre de Cali Plaza",
    "MVD": "Ibis Montevideo Rambla",
    "ASU": "Factoria Hotel",
    "SAT": "Drury Plaza Hotel San Antonio Riverwalk",
    "AUS": "Four Seasons Hotel",
    "HOU": "Marriott Marquis",
    "MSY": "The Lafayette by Kasa",
    "SJU": "Tropica Beach Hotel",
    "TPA": "Grand Hyatt Tampa Bay",
    "PIE": "The Ponce De Leon Hotel",
    "FLL": "Ocean Mile Hotel & Suites",
    "PBI": "The Breakers Palm Beach",
    "DAY": "Holiday Inn Express & Suites",
    "TOL": "Quality Inn Holand",
    "CAK": "Berrodin Bed & Breakfast",
    "LEX": "Marriott City Center",
    "SDF": "The Seelbach Hilton",
    "CHS": "Harbor Resort & Marina",
    "SAV": "Perry Lane Hotel",
    "GSP": "Grand Bohemian Lodge",
    "TYS": "The Tennessean Personal Luxury Hotel",
    "CHA": "The Read House",
    "HSV": "Marriott at the Space & Rocket Center",
    "MOB": "Fort Conde Inn",
    "PNS": "Oyster Bay Boutique Hotel",
    "SAF": "La Fonda on the Plaza",
    "DRO": "The General Palmer Hotel",
    "FLG": "High Country Motor Lodge",
    "YUM": "Garden Inn Yuma Pivot Point",
    "LPB": "Suites Camino Real",
    "CBB": "Gran Hotel Cochabamba",
    "BAQ": "Movich Buro 51",
    "MZL": "Estelar Recinto del Pensamiento",
    "CUE": "Cruz del Vado",
    "SLA": "Kkala Boutique Hotel",
    "MDZ": "Cavas Wine Lodge",
    "USH": "Las Hayas Ushuaia Resort",
    "PUQ": "Hotel Cabo de Hornos",
    "ANF": "Terrado Antofagasta",

    # Europe
    "AMS": "Hotel TwentySeven",
    "ATH": "Hotel Grande Bretagne",
    "BCN": "EI Palace Hotel",
    "BER": "Radisson Collection Hotel",
    "BRU": "Le Dixseptieme Hotel",
    "CPH": "Manon Les Suites",
    "DUB": "The Merrion Hotel",
    "EDI": "Kimpton Charlotte Square Hotel",
    "FRA": "Hilton Frankfurt Gravenbruch",
    "GVA": "The Woodward, Auberge Collection",
    "HEL": "Waldorf Astoria",
    "IST": "Sultanahmet Historical Guesthouse",
    "LIS": "Pestana Palace",
    "LON": "West End Value Lodge",
    "MAD": "The Principal Madrid Hotel",
    "MAN": "The Lowry Hotel",
    "MIL": "Palazzo Parigi Hotel",
    "MOW": "Hyatt Regency Moscow Petrovsky Park",
    "MUC": "Hotel Bayerischer Hof",
    "OSL": "Lysebu Hotel",
    "PAR": "Charming Parisian Boutique",
    "PRG": "Hotel Caesar",
    "ROM": "Fendi Private Suites",
    "LED": "Corinthia Hotel",
    "STO": "Nobis Hotel",
    "VIE": "Anantara Palais Hansen Hotel",
    "WAW": "Raffles Europejski",
    "ZRH": "The Dolder Grand",
    "GOT": "Jumeirah (tidl. Clarion Hotel Post)",
    "MMX": "Elite Hotel Renaissance",
    "BLL": "The Lodge Billund",
    "AAL": "Radisson Blu Limfjord Hotel",
    "TLL": "Swissotel Tallinn",
    "RIX": "Pullman Riga Old Town",
    "VNO": "Grand Hotel Kempinski",
    "KRK": "Hotel Copernicus",
    "GDN": "Puro Hotel Gdansk Stare Miasto",
    "WRO": "The Bridge Wroclaw MGallery",
    "BUD": "Anantara New York Palace",
    "OTP": "Grand Hotel Continental",
    "CLJ": "DoubleTree by Hilton City Centre",
    "SOF": "InterContinental Sofia",
    "BEG": "Square Nine Hotel",
    "SKG": "Makedonia Palace",
    "HER": "GDM Megaron Historical Monument Hotel",
    "RHO": "Mitsis Grand Hotel",
    "NAP": "Grand Hotel Vesuvio",
    "FLR": "Westin Excelsior",
    "BLQ": "Art Hotel Commercianti",
    "PSA": "Hotel Relais Dell'Orologio",
    "TRN": "Turin Palace Hotel",
    "VRN": "Hotel Gabbia d'Oro",
    "INN": "Stage 12 Hotel by Penz",
    "SZG": "Hotel Goldener Hirsch",
    "GRZ": "Schlossberghotel - Das Kunsthotel",
    "LJU": "Zlata Ladjica Boutique Hotel",
    "ZAG": "Esplanade Zagreb Hotel",
    "SPU": "Heritage Hotel Santa Lucia",
    "DBV": "Hotel Bellevue",
    "TIA": "Maritim Hotel Plaza Tirana",
    "SJJ": "Pino Nature Hotel",
    "VLC": "Las Arenas Balneario Resort",
    "ALC": "Casa Alberola Alicante",
    "PMI": "Convent de la Missio",
    "IBZ": "Nobu Hotel Ibiza Bay",
    "KEF": "The Reykjavik EDITION",
    "HAM": "Hotel Atlantic Hamburg",
    "NCE": "Hotel Le Negresco",
    "BGO": "Det Hanseatiske Hotel",
    "LUX": "Le Royal Hotels & Resorts",
    "BSL": "Hyperion Hotel Basel",
    "BRN": "Bellevue Palace",
    "TKU": "Radisson Blu Marina Palace",
    "TMP": "Solo Sokos Hotel Torni",
    "OUL": "Lapland Hotels",
    "BOO": "Quality Hotel Ramsalt",
    "TOS": "Clarion Hotel The Edge",
    "UME": "Elite Hotel Mimer",
    "VBY": "Donners Hotell",
    "ODE": "Comwell H. C. Andersen Hotel",
    "EBJ": "Hjerting Badehotel",
    "GRQ": "Hotel de Ville",
    "EIN": "Inntel Hotels Art Eindhoven",
    "RTM": "The Slaak Rotterdam",
    "BES": "Hotel Oceania Brest Centre",
    "RNS": "Le Saint-Antoine Hotel & Spa",
    "LIG": "Novotel Limoges Le Lac",
    "ZAZ": "Alfonso Hotel",
    "RMU": "Hesperia Murcia Centro",
    "LEI": "Ohtels Gran Hotel Almeria",
    "XRY": "Hotel Casa Palacio Maria Luisa",
    "TRS": "Savoia Excelsior Palace",
    "PEG": "Sina Brufani",
    "AOI": "Grand Hotel Passetto",
    "SUF": "TUI BLUE Tropea",
    "BRI": "The Nicolaus Hotel",
    "CAG": "Palazzo Doglio",
    "OLB": "Hotel Felix Olbia",
    "PDV": "The Emporium Plovdiv - MGallery",
    "VAR": "Grand Hotel London",
    "TSR": "Tresor Le Palais",
    "OMR": "DoubleTree by Hilton Oradea",
    "KSC": "Hotel Yasmin",
    "KRR": "Marriott Krasnodar Hotel",
    "AER": "Radisson Blu Paradise Resort & Spa",
    "SVQ": "Hotel Palacio de Villapanes",
    "GRX": "Hospes Palacio de los Patos",
    "AGP": "Only YOU Hotel Malaga",
    "BIO": "Gran Hotel Domine Bilbao",
    "SDR": "Eurostars Hotel Real",
    "FAO": "Hotel Eva Senses",
    "OPO": "Torel Palace Porto",
    "CBP": "Hotel Sapientia Boutique Hotel",
    "LYS": "Cour des Loges",
    "MRS": "Sofitel Marseille Vieux Port",
    "TLS": "Pullman Toulouse Centre Ramblas",
    "MPL": "Pullman Montpellier Centre",
    "AVN": "La Mirande",
    "CGN": "Excelsior Hotel Ernst",
    "STR": "Steigenberger Graf Zeppelin",
    "DRS": "Hotel Bulow Palais",
    "LEJ": "The Westin Leipzig",
    "NUE": "Adina Apartment Hotel",
    "LBA": "Quebecs Hotel",
    "BRS": "Harbour Hotel Bristol",
    "CWL": "The Parkgate Hotel",
    "BFS": "The Fitzwilliam Hotel",
    "ORK": "The Montenotte Hotel",
    "SNN": "The Clayton Hotel Limerick",
    "BTS": "Marrol's Boutique Hotel",
    "KTW": "Vienna House Easy by Wyndham",
    "LCJ": "Puro Hotel Lodz",
    "POZ": "Sheraton Poznan Hotel",
    "BRQ": "Grandezza Hotel Luxury Palace",
    "OSR": "Imperial Hotel Ostrava",
    "SKP": "Bushi Resort & Spa",

    # Asia & Middle East
    "AUH": "Saadiyat Rotana Resort & Villas",
    "AMM": "Kempinski Hotel Ishtar Dead Sea",
    "BKK": "Sukhumvit Budget Stay",
    "PEK": "VUE Hotel Hou Hai",
    "BLR": "The Leela Palace",
    "CTU": "Mumian Chengdu Dong'an Lake",
    "DEL": "Connaught Place Mid-Range Inn",
    "DPS": "Harsono Boutique Resort",
    "DOH": "The Chedi Katara Hotel",
    "DXB": "Desert View Residence",
    "SGN": "New World Saigon Hotel",
    "HKG": "The Langham Hotel",
    "HYD": "Taj Krishna",
    "CGK": "Hotel Indonesia Kempinski",
    "KUL": "Banyan Tree Hotel",
    "KWI": "Marriott Executive Apartments",
    "MNL": "City Garden GRAND Hotel Makati",
    "BOM": "Gateway Comfort Suites",
    "OSA": "Quintessa Hotel Osaka Bay",
    "HKT": "The Nchantra Pool Suite",
    "RUH": "Al Mashreq Boutique Hotel",
    "SEL": "Lotte Hotel World",
    "SHA": "Hyatt on the Bund Hotel",
    "SIN": "The Fullerton Hotel",
    "TPE": "Sheraton Grand Taipei Hotel",
    "TYO": "Shinjuku Business Inn",
    "PNQ": "JW Marriott Hotel Pune",
    "CCU": "The Oberoi Grand",
    "AMD": "ITC Narmada",
    "COK": "Brunton Boatyard",
    "TRV": "Hyatt Regency Trivandrum",
    "IXC": "The Oberoi Sukhvilas",
    "PAT": "Hotel Maurya",
    "VNS": "Taj Nadesar Palace",
    "JAI": "Jai Mahal Palace",
    "UDR": "The Leela Palace Udaipur",
    "NAG": "Radisson Blu Hotel",
    "MAA": "ITC Grand Chola",
    "GOI": "Taj Exotica Resort & Spa",
    "IDR": "Indore Marriott Hotel",
    "JDH": "Umaid Bhawan Palace",
    "AGR": "ITC Mughal",
    "ATQ": "Taj Swarna",
    "IXU": "Ambassador Ajanta",
    "IXM": "Courtyard by Marriott",
    "TIR": "Marasa Sarovar Premiere",
    "IXL": "Stok Palace Heritage Hotel",
    "DED": "Seyfert Sarovar Portico",
    "IXJ": "Vivanta Jammu, City Centre",
    "STV": "The Gateway Hotel Athwalines",
    "BDQ": "Welcomhotel by ITC Hotels",
    "RAJ": "Fortune Park JPS Grand",
    "BHO": "Jehan Numa Palace Hotel",
    "RPR": "Mayfair Lake Resort",
    "IXR": "Chanakya BNR Hotel",
    "PNY": "Palais de Mahe",
    "KUU": "Baragarh Resort & Spa",
    "PEN": "Eastern & Oriental Hotel",
    "LGK": "The Datai Langkawi",
    "SUB": "Hotel Majapahit Surabaya",
    "BDO": "The Trans Luxury Hotel",
    "KNO": "Grand City Hall Hotel & Serviced Residences",
    "HAN": "InterContinental Hanoi Westlake",
    "DAD": "TIA Wellness Resort",
    "CXR": "Amiana Resort Nha Trang",
    "PNH": "The Flora Boutique Hotel",
    "REP": "Phum Baitang",
    "ICN": "Paradise City",
    "PUS": "Ananti at Busan Cove",
    "CJU": "The Shilla Jeju",
    "KHI": "Pearl Continental Hotel",
    "LHE": "Avari Lahore Hotel",
    "ISB": "Serena Hotel Islamabad",
    "MCT": "Shangri-La Al Husn",
    "IKA": "Parsian Azadi Hotel",
    "JED": "Waldorf Astoria Jeddah - Qasr Al Sharq",
    "DMM": "Kempinski Al Othman Hotel Al Khobar",
    "KTM": "Dwarika's Hotel",
    "CMB": "Galle Face Hotel",
    "DAC": "Pan Pacific Sonargaon Dhaka",
    "ALA": "Rixos Almaty Hotel",
    "TAS": "Hilton Tashkent City",
    "SKD": "DiliMah Premium Luxury",
    "GYD": "Fairmont Baku, Flame Towers",
    "BUS": "Sheraton Batumi Hotel",
    "EVN": "Marriott Armenia Hotel Yerevan",
    "ULN": "Terelj Hotel",
    "LPQ": "Belmond La Residence Phou Vao",
    "VTE": "Settha Palace Hotel",
    "MDL": "Mercure Mandalay Hill Resort",
    "NYU": "Aureum Palace Hotel & Resort",
    "TAE": "Hotel Inter Burgo Exco",
    "KWJ": "Ramada Plaza Gwangju",
    "FUK": "Miyako Hotel Hakata",
    "SDJ": "Sendai Royal Park Hotel",
    "CTS": "The Prince Park Tower",
    "KOJ": "Sun Royal Hotel",
    "OKJ": "Ana Crowne Plaza",
    "BKI": "The Magellan Sutera Resort",
    "KCH": "The Waterfront Hotel",
    "PNK": "Golden Tulip Pontianak",
    "BPN": "Gran Senyiur Hotel",
    "UPG": "Mercure Makassar Nexa Pettarani",
    "PDG": "The ZHM Premiere DH Thamrin",
    "PKU": "Labersa Grand Hotel & Convention Center",
    "LKO": "Lebua Lucknow",
    "KNU": "Status Business Hotel",
    "GAU": "Kiranshree Grand",
    "IMF": "The Classic Hotel",
    "AJL": "Hotel Regency",
    "SHL": "Ri Kynjai - Serenity by the Lake",
    "IXS": "Hotel Borail View",
    "DIB": "Radha Residency",
    "JRH": "Kaziranga Golf Resort",
    "DMU": "Hotel Tragopan",
    "IXA": "Hotel Polo Towers",
    "VGA": "Novotel Vijayawada Varun",
    "VTZ": "Novotel Visakhapatnam Varun Beach",
    "RJA": "Shelton Rajamahendri",
    "TRZ": "Sangam Hotel",
    "CJB": "The Residency Towers",
    "SXV": "Sivaraj Inn",
    "TCR": "Senthil Residency",
    "MYQ": "Radisson Blu Plaza Hotel",
    "HBX": "Denissons Hotel",
    "IXG": "Fairfield by Marriott Belagavi",
    "GBI": "Hotel Lumbini's Grand",
    "IXE": "The Ocean Pearl",
    "UDU": "Fortune Inn Valley View",
    "BTH": "Marriott Hotel Harbour Bay",
    "JOG": "The Phoenix Hotel",
    "SOC": "The Royal Surakarta Heritage",
    "SRG": "Gumaya Tower Hotel",
    "PLM": "Wyndham Opi Hotel",
    "HDY": "Centara Hotel",
    "CEI": "Mora Boutique Hotel",
    "UTH": "The Pannarai Hotel",
    "VVO": "Tiger de Cristal Resort & Casino",
    "KHV": "Riviera Wellness Resort",
    "TUU": "Grand Millennium",
    "YNB": "Movenpick Hotel & Resort",
    "AHB": "The Blue Inn Hotel",
    "TIF": "Iridium Hotel",
    "IKT": "History Boutique Hotel & Spa",
    "NOZ": "Bardot Hotel",
    "ULH": "Shaden Resort",

    # Africa & Oceania
    "ACC": "Movenpick Ambassador Hotel",
    "ADL": "Eos by SkyCity",
    "AKL": "Sofitel Auckland Viaduct Harbour",
    "CAI": "Pyramisa Suites Hotel",
    "CPT": "Taj Cape Town",
    "CMN": "Le Casablanca Hotel",
    "DUR": "Essenwood House",
    "JNB": "AtholPlace Hotel & Villa",
    "RAK": "PALAIS ALCAZAR",
    "MEL": "Crown Towers",
    "NBO": "Gem Forest Hotel",
    "PER": "COMO The Treasury",
    "SYD": "Shangri-La Hotel",
    "TUN": "Sheraton Tunis Hotel",
    "WLG": "Bay of Many Coves Resort",
    "LOS": "The Wheatbaker",
    "ABV": "Transcorp Hilton Abuja",
    "PHC": "Swiss Spirit Hotel & Suites Danag",
    "LAD": "Epic Sana Luanda Hotel",
    "MPM": "Polana Serena Hotel",
    "GBE": "Hilton Garden Inn Gaborone City Centre",
    "WDH": "The Weinberg Windhoek",
    "HRE": "Meikles Hotel",
    "ADD": "Sheraton Addis",
    "DSS": "Pullman Dakar Teranga",
    "BNE": "The Calile Hotel",
    "OOL": "The Langham, Gold Coast",
    "CNS": "Crystalbrook Riley",
    "HBA": "The Henry Jones Art Hotel",
    "LST": "Peppers Silo Hotel",
    "CHC": "Sudima Christchurch City",
    "DUD": "Distinction Dunedin Hotel",
    "NAN": "Fiji Marriott Resort Momi Bay",
    "PPT": "Hilton Hotel Tahiti",
    "POM": "Grand Papua Hotel",
    "MLE": "Kurumba Maldives",
    "PLZ": "The Boardwalk Hotel",
    "ELS": "Premier Hotel Regent",
    "PTG": "Fusion Boutique Hotel",
    "LVI": "Avani Victoria Falls Resort",
    "NLA": "Garden Court Kitwe",
    "EBB": "Protea Hotel by Marriott Entebbe",
    "KGL": "The Retreat by Heaven",
    "BJM": "Kiriri Garden Hotel",
    "HAH": "Retaj Moroni Hotel",
    "TNR": "Novotel Convention & Spa Antananarivo",
    "NOS": "Andilana Beach Resort",
    "TSV": "The Ville Resort-Casino",
    "ROK": "Empire Apartment Hotel",
    "DRW": "Mindil Beach Casino Resort",
    "ASP": "DoubleTree by Hilton Alice Springs",
    "ZQN": "The Rees Hotel & Luxury Apartments",
    "ROT": "Pullman Rotorua",
    "IVC": "The Langlands Hotel",
    "APW": "Sheraton Samoa Aggie Grey's Hotel & Bungalows",
    "HIR": "Heritage Park Hotel",
    "MRU": "Labordonnais Waterfront Hotel",
    "SEZ": "Fisherman's Cove Resort",
    "LLW": "Radisson Blu Hotel",
    "BLZ": "Protea Hotel by Marriott Ryalls",
    "LUN": "President Walmont Hotel",
    "BUQ": "The Nesbitt Castle",
    "FRW": "Cresta Marang Gardens",
    "WVB": "Strand Hotel Swakopmund",
    "SWP": "Hamanasi Guesthouse",
    "ARK": "Gran Melia Arusha",
    "JRO": "Arusha Coffee Lodge",
    "MBA": "Sarova Whitesands Beach Resort & Spa",
    "ZNZ": "Park Hyatt Zanzibar",
    "DAR": "Johari Rotana",
    "CBR": "Hotel Realm",
    "ABX": "Quest Albury on Townsend",
    "WGA": "The Houston",
    "DBO": "The Oxley Centennial Motel",
    "KGI": "The Palace Hotel",
    "BME": "The Pearle of Cable Beach",
    "NSN": "The Rutherford Hotel",
    "TUO": "Sacred Waters Luxury Apartments",
    "WRE": "Lodge Bordeaux",
    "TIU": "The Grosvenor Hotel",

    "DEFAULT": "The Grand Central Inn"
}
